### ISSUE TITLE
use @parallelize on a class, but when I use a function of this class, parallel looks like didn't work

### ISSUE THREAD

**Issue by 741311791** [aelskens/ray-ease#3]
my code:
```Python
ray_ease_init()
    
@parallelize
class Prime:
    # Constructor
    def __init__(self,number) :
        self.num = number
    
    def SumPrime(self,num) :
        time.sleep(1)
        return num*2
            
num = 10
start = time.time()
prime = Prime(num)

results = retrieve_parallel_loop([prime.SumPrime(10) for x in range(4)])
print("duration =", time.time() - start)
print("results =", results)
```
运行结果：
duration = 4.852661609649658
results = [20, 20, 20, 20]

ray official code:
```Python
ray_ease_init()
    
@ray.remote
class Prime:
    # Constructor
    def __init__(self,number) :
        self.num = number
    
    def SumPrime(self,num) :
        time.sleep(1)
        return num*2
            
num = 10
start = time.time()
# make an object of Check class
prime = Prime.remote(num)

results = ray.get(prime.SumPrime.remote(num))
print("duration =", time.time() - start)
print("results =", results)
```
运行结果：
duration = 1.8083322048187256
results = 20

**Comment by aelskens** [comment]
Hi @741311791,

Thank you for your interest in this package!

Regarding your issue, it is completely normal as you are not comparing the same pieces of code. In the first one, you execute `SumPrime` four times due to `range(4)`. In the second one, you only call it once.

Here is the second code cell adapted to run the same code as the first one:

```Python
ray_ease_init()

@ray.remote
class Prime:
    # Constructor
    def __init__(self, number):
        self.num = number

    def SumPrime(self, num):
        time.sleep(1)
        return num * 2

num = 10
start = time.time()
# make an object of Check class
prime = Prime.remote(num)

# I have changed, hereunder, your code cell to get the same execution as the first one
results = ray.get([prime.SumPrime.remote(num) for _ in range(4)])
print("duration =", time.time() - start)
print("results =", results)
```

This yields the same results as the first cell you have provided:
>duration = 4.789142608642578
>results = [20, 20, 20, 20]

The reason behind this is that by decorating your class, you are able to utilize multiple instances of this class in parallel. However, the class methods themselves are not used in parallel within the instances, this explains that you get over 4 seconds of duration. 

To actually parallelize this specific method you should write something similar to this:

```Python
ray_ease_init()

class Prime:
    # Constructor
    def __init__(self, number):
        self.num = number

    @parallelize
    def _double(self, num):
        time.sleep(1)
        return num * 2

    def SumPrime(self, num, loop_range):
        return retrieve_parallel_loop([__class__._double(self, num) for _ in range(loop_range)])

num = 10
start = time.time()
prime = Prime(num)

results = prime.SumPrime(10, 4)
print("duration =", time.time() - start)
print("results =", results)
```

Which yields this time:
>duration = 1.0471312999725342
>results = [20, 20, 20, 20]

Note that it is a bit strange how to call the `_double` method (see #2 for the work around), this is entirely due to how `ray.remote` works behind the scene.

**Comment by aelskens** [comment]
By the way, please not that I have just published a new version of `ray-ease` onto PyPI which eases a bit the usage of `ray-ease`. To see what has changed checkout the examples from the [README](https://github.com/aelskens/ray-ease/blob/main/README.md)).
